"""Frozen constants for the 3C-SiC(001) Si-face vertical slice."""

PLUGIN_ID = "sic_3c_001_si_face_surface"
CONTRACT_VERSION = "1.0.0"
IMPLEMENTATION_VERSION = "1.0.0"

MATERIAL = "3C-SiC"
SCENARIO = "surface_slab"
OPERATION = "create_si_face_slab"
SOURCE_ID = "cod-1010995"

BULK_LATTICE_ANGSTROM = 4.3596
IN_PLANE_REPEAT = 2
BILAYER_COUNT = 4
ATOMIC_PLANE_COUNT = 8
VACUUM_ANGSTROM = 15.0
CARBON_HYDROGEN_BOND_ANGSTROM = 1.09
BOTTOM_CARBON_COUNT = 8
HYDROGENS_PER_BOTTOM_CARBON = 2
SILICON_COUNT = 32
CARBON_COUNT = 32
HYDROGEN_COUNT = 16
TOTAL_ATOM_COUNT = 80

__all__ = [
    "ATOMIC_PLANE_COUNT",
    "BILAYER_COUNT",
    "BOTTOM_CARBON_COUNT",
    "BULK_LATTICE_ANGSTROM",
    "CARBON_COUNT",
    "CARBON_HYDROGEN_BOND_ANGSTROM",
    "CONTRACT_VERSION",
    "HYDROGEN_COUNT",
    "HYDROGENS_PER_BOTTOM_CARBON",
    "IMPLEMENTATION_VERSION",
    "IN_PLANE_REPEAT",
    "MATERIAL",
    "OPERATION",
    "PLUGIN_ID",
    "SCENARIO",
    "SILICON_COUNT",
    "SOURCE_ID",
    "TOTAL_ATOM_COUNT",
    "VACUUM_ANGSTROM",
]
